//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Attendee
{
    public int Id { get; set; }
    public string Company { get; set; }
    public string Initials { get; set; }
    public string Surname { get; set; }
    public string Emailaddress { get; set; }
    public bool HasCoupon { get; set; }
    public bool HasPaid { get; set; }
    public string Contract { get; set; }
    public int Zaterdag { get; set; }
    public int Zondag { get; set; }
    public int Maandag { get; set; }
    public int PassePartout { get; set; }
    public byte[] Barcode { get; set; }

    public virtual Profession AttendeeProfession { get; set; }
}

public partial class Profession
{
    public int Attendee_Id { get; set; }
    public Nullable<bool> Professional { get; set; }
    public Nullable<bool> SemiProfessional { get; set; }
    public Nullable<bool> Retail { get; set; }
    public Nullable<bool> Student { get; set; }
    public Nullable<bool> Overig { get; set; }

    public virtual Attendee Attendee { get; set; }
}
