//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Attendee
{
    public int Id { get; set; }
    public string Company { get; set; }
    public Nullable<int> Profession { get; set; }
    public string Initials { get; set; }
    public string Surname { get; set; }
    public string Emailaddress { get; set; }
    public bool HasCoupon { get; set; }
    public bool HasPaid { get; set; }
    public string Contract { get; set; }
}
